FROM node:14.17-alpine as builder

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . ./ 
ENV REACT_APP_API_URL http://192.168.1.112:5000

RUN npm run build

FROM nginx AS server
COPY --from=builder /app/build /usr/share/nginx/html